name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Login to Azure'
      uses: azure/login@v1.4.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Get Azure Static Web Apps API Token'
      - name: 'Get Azure Static Web Apps API Token'
        id: get_token
        run: |
          token=$(az account get-access-token --query accessToken -o tsv)
          echo "Azure Token: $token"
          echo "token=$token" >> $GITHUB_ENV


    - name: 'Deploy to Azure Static WebApp'
      uses: Azure/static-web-apps-deploy@v1.0.0
      with:
        azure_static_web_apps_api_token: ${{ env.token }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/'
        output_location: 'dist'
