name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: 'Login to Azure'
      uses: azure/login@v1.4.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Get Azure Static Web Apps Deployment Token'
      id: get_token
      run: |
        app_name="${{ vars.STATIC_WEBAPP_NAME }}"
        token=$(az staticwebapp secrets list --name $app_name --query properties.apiKey -o tsv)        
        echo "token=$token" >> $GITHUB_ENV


    - name: 'Deploy to Azure Static WebApp'
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.token }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: '/'
        output_location: 'dist'
